/*
Copyright (c) 2010, NHIN Direct Project
All rights reserved.

Authors:
   Greg Meyer      gm2552@cerner.com

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the distribution.  Neither the name of the The NHIN Direct Project (nhindirect.org).
nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
THE POSSIBILITY OF SUCH DAMAGE.
*/

package org.nhindirect.monitor.entity;

import java.util.Calendar;
import java.util.Locale;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * DAO entity object representing a DSN that was generated by the message monitor due to a completion timeout, and is awaiting
 * confirmation that the gateway has tracked (and therefore acted on) it before a corresponding entry is written to the
 * {@link ReceivedNotification} duplicate store.  A row is created when the DSN is generated and removed once the DSN is
 * seen coming back through message tracking.  Rows that are never confirmed indicate that a generated DSN was lost before
 * it could be tracked by the gateway.
 * @author Greg Meyer
 * @since 9.1
 */
@Entity
@Table(name = "pendingnotification", indexes = {@Index(name="i_dsnmessageid", columnList="dsnmessageid"),
	    @Index(name="i_createdtime",columnList="createdtime")})
public class PendingNotification
{
    private long id = 0L;
	private String dsnMessageId;
	private String originalMessageId;
	private String address;
	private Calendar createdTime;

	/**
	 * Default constructor
	 */
	public PendingNotification()
	{

	}

    /**
     * Get the value of id.
     *
     * @return the value of id.
     */
    @Id
    @Column(name = "id", nullable = false)
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long getId()
    {
        return id;
    }

    /**
     * Set the value of id.
     *
     * @param id
     *            The value of id.
     */
    public void setId(long id)
    {
        this.id = id;
    }

	/**
	 * Gets the message id of the generated DSN.  This is the id that will reappear on the DSN when it is later tracked
	 * by the gateway, and is used to correlate the tracked DSN back to this pending record.
	 * @return The message id of the generated DSN.
	 */
    @Column(name = "dsnmessageid", nullable = false)
	public String getDsnMessageId()
	{
		return dsnMessageId.toLowerCase(Locale.getDefault());
	}

    /**
     * Sets the message id of the generated DSN.
     * @param dsnMessageId The message id of the generated DSN.
     */
    public void setDsnMessageId(String dsnMessageId)
    {
    	this.dsnMessageId = dsnMessageId.toLowerCase(Locale.getDefault());
    }

	/**
	 * Gets the message id of the original message that the generated DSN pertains to.
	 * @return The message id of the original message.
	 */
    @Column(name = "originalmessageid", nullable = false)
	public String getOriginalMessageId()
	{
		return originalMessageId.toLowerCase(Locale.getDefault());
	}

    /**
     * Sets the message id of the original message that the generated DSN pertains to.
     * @param originalMessageId The message id of the original message.
     */
    public void setOriginalMessageId(String originalMessageId)
    {
    	this.originalMessageId = originalMessageId.toLowerCase(Locale.getDefault());
    }

    /**
     * Gets the email address of the final recipient that the generated DSN pertains to.
     * @return The email address of the final recipient.
     */
    @Column(name = "address", nullable = false)
    public String getAddress()
    {
    	return address.toLowerCase(Locale.getDefault());
    }

    /**
     * Sets the email address of the final recipient that the generated DSN pertains to.
     * @param address The email address of the final recipient.
     */
    public void setAddress(String address)
    {
    	this.address = address;
    }

    /**
     * Gets the time the pending record was created.
     * @return The time the pending record was created.
     */
    @Column(name = "createdtime")
    @Temporal(TemporalType.TIMESTAMP)
    public Calendar getCreatedTime()
    {
    	return this.createdTime;
    }

    /**
     * Sets the time the pending record was created.
     * @param time The time the pending record was created.
     */
    public void setCreatedTime(Calendar time)
    {
    	createdTime = (Calendar) time.clone();
    }
}
