package org.nhindirect.monitor.processor.impl;

import java.util.Arrays;
import java.util.Calendar;
import java.util.Collection;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import jakarta.mail.internet.MimeMessage;

import org.apache.camel.Exchange;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.nhindirect.common.mail.MDNStandard;
import org.nhindirect.common.tx.TxUtil;
import org.nhindirect.common.tx.impl.DefaultTxDetailParser;
import org.nhindirect.common.tx.model.Tx;
import org.nhindirect.common.tx.model.TxDetail;
import org.nhindirect.common.tx.model.TxDetailType;
import org.nhindirect.common.tx.model.TxMessageType;
import org.nhindirect.monitor.condition.impl.AbstractCompletionCondition;
import org.nhindirect.monitor.entity.PendingNotification;
import org.nhindirect.monitor.processor.DuplicateNotificationStateManagerException;
import org.nhindirect.monitor.repository.PendingNotificationRepository;
import org.nhindirect.monitor.repository.RepositoryBiz;

import lombok.extern.slf4j.Slf4j;

/**
 * Extended implementation of the DefaultDuplicateNotificationStateManager that handles DSN messages generated by 
 * the message monitor and properly handles tracking of DSN messages generated by the message monitor.
 * @author Greg Meyer
 * @since 1.1.4
 */
@Slf4j
public class TimeoutDupStateManager extends DefaultDuplicateNotificationStateManager
{
	@SuppressWarnings("deprecation")
	private static final Log LOGGER = LogFactory.getFactory().getInstance(TimeoutDupStateManager.class);

	protected static final int DEFAULT_PENDING_RETENTION_TIME = 24;

	protected final DefaultTxDetailParser parser;

	protected PendingNotificationRepository pendingRepo;

	protected int pendingMessageRetention;

	/**
	 * Default contructor
	 */
	public TimeoutDupStateManager()
	{
		super();

		parser = new DefaultTxDetailParser();
		pendingMessageRetention = DEFAULT_PENDING_RETENTION_TIME;
	}

	/**
	 * Sets the repository used to track DSNs generated by the message monitor that are pending confirmation
	 * (via message tracking) before a corresponding entry is written to the duplicate notification store.
	 * @param pendingRepo The pending notification repository.
	 */
	public void setPendingNotificationRepository(PendingNotificationRepository pendingRepo)
	{
		this.pendingRepo = pendingRepo;
	}

	/**
	 * Sets the time in hours that a pending notification (a generated DSN awaiting confirmation that the gateway
	 * has tracked it) is allowed to remain unconfirmed before being purged.
	 * @param pendingMessageRetention The time in hours that a pending notification may remain unconfirmed.
	 */
	public void setPendingMessageRetention(int pendingMessageRetention)
	{
		this.pendingMessageRetention = pendingMessageRetention;
	}
	
	
	/**
	 * Adds a duplication state entry for each recipient of the original message
	 * @param txs Collection of message transactions.  The original message must be present in the collection
	 * @throws DuplicateNotificationStateManagerException
	 */
	public void addNotificationForOriginalRecips(Collection<Tx> txs) throws DuplicateNotificationStateManagerException
	{
		if (recRepo == null)
			throw new IllegalArgumentException("Dao cannot be null");	
		
		if (txs == null)
			throw new IllegalArgumentException("Txs cannot be null");
		
		final Tx tx = AbstractCompletionCondition.getMessageToTrack(txs);
		
		if (tx != null && TxUtil.isReliableAndTimelyRequested(tx))
		{
			final TxDetail recipDetail = tx.getDetail(TxDetailType.RECIPIENTS);
			final TxDetail msgId = tx.getDetail(TxDetailType.MSG_ID);
			
			if (recipDetail != null && msgId != null)
			{
				final String[] recips = recipDetail.getDetailValue().split(",");
				for (String recip : recips)
				{
					
					try
					{
						final String normalizedFinalRecip = AbstractCompletionCondition.normalizeFinalRecip(recip);
						RepositoryBiz.addMessageToDuplicateStore(msgId.getDetailValue(), normalizedFinalRecip, recRepo);
					}
					///CLOVER:OFF
					catch (Exception e)
					{
						LOGGER.warn("Can't add recipient " + recip + " for message id " + msgId.getDetailValue() 
								+ " to dup store.  Possibly already exists in dup store.");
					}
					///CLOVER:ON
				}
			}
		}
	}
	
	/**
	 * Adds a duplication state entry for each final recipient in a DSN message that was generated by the message monitor
	 * @param dsnMessage The DSN message
	 * @param ex The aggregation exchange.  The property "ORGI_IS_TIMELY" is checked to see if this DSN is part of a timely and reliable
	 * exchange
	 * @throws DuplicateNotificationStateManagerException
	 */
	public void addNotificationForMonitorGeneratedDSN(MimeMessage dsnMessage, Exchange ex) throws DuplicateNotificationStateManagerException
	{
		if (recRepo == null)
			throw new IllegalArgumentException("Dao cannot be null");

		if (pendingRepo == null)
			throw new IllegalArgumentException("Pending notification repository cannot be null");

		if (dsnMessage == null)
		{
			log.debug("Null DNS message.  Ignoring message.");
			return;
		}
		
		if (TxUtil.getMessageType(dsnMessage).equals(TxMessageType.DSN) && ex.getProperty("ORIG_IS_TIMELY") != null)
		{
			final Map<String, TxDetail> details = parser.getMessageDetails(dsnMessage);
			
			final TxDetail origMsgId = details.get(TxDetailType.PARENT_MSG_ID.getType());
			final TxDetail finalRecipDetail = details.get(TxDetailType.FINAL_RECIPIENTS.getType());
			final TxDetail msgId = details.get(TxDetailType.MSG_ID.getType());
			
			if (origMsgId != null && finalRecipDetail != null && msgId != null)
			{
				final String[] finalRecips = finalRecipDetail.getDetailValue().split(",");
				for (String finalRecip : finalRecips)
				{
					try
					{
						final String normalizedFinalRecip = AbstractCompletionCondition.normalizeFinalRecip(finalRecip);

						// Don't write directly to the duplicate store yet.  The DSN generated here still has to make
						// it through the gateway (send, suppression check, and last mile delivery), and none of that
						// is guaranteed to succeed.  Record it as pending instead; the entry is promoted to the
						// duplicate store once the gateway tracks this DSN back to the monitor, confirming the
						// gateway actually acted on it.
						RepositoryBiz.addMessageToPendingNotificationStore(msgId.getDetailValue(), origMsgId.getDetailValue(),
								normalizedFinalRecip, pendingRepo);
					}
					///CLOVER:OFF
					catch (Exception e)
					{
						LOGGER.warn("Can't add recipient " + finalRecip + " for message id " + msgId.getDetailValue()
								+ " to pending notification store.  Possibly already exists in pending notification store.");
					}
					///CLOVER:ON
				}
			}
		}
		
	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean suppressNotification(Tx notificationMessage) throws DuplicateNotificationStateManagerException
	{
		boolean retVal = false;

		if (recRepo == null)
			throw new IllegalArgumentException("Dao cannot be null");

		if (pendingRepo == null)
			throw new IllegalArgumentException("Pending notification repository cannot be null");

		if (notificationMessage == null)
			throw new IllegalArgumentException("Notification message cannot be null");

		final TxMessageType type = notificationMessage.getMsgType();


		if (type == TxMessageType.DSN || type == TxMessageType.MDN)
		{
			final TxDetail dispositionDetail = notificationMessage.getDetail(TxDetailType.DISPOSITION);

			// if it's an MDN displayed, then don't suppress it and let it go through
			if (type == TxMessageType.MDN && (dispositionDetail == null || dispositionDetail.getDetailValue().contains(MDNStandard.Disposition_Displayed)))
				return retVal;

			final TxDetail originalMessageIdDetail = notificationMessage.getDetail(TxDetailType.PARENT_MSG_ID);
			final TxDetail origRecips = notificationMessage.getDetail(TxDetailType.FINAL_RECIPIENTS);

			if (originalMessageIdDetail != null && origRecips != null)
			{
				// If this is a DSN and its own message id has a pending notification entry, then this is a DSN that
				// the monitor itself generated on a timeout, making its first pass back through the gateway.  Promote
				// its pending entries to the duplicate store now that the gateway has taken up the message, but don't
				// suppress the DSN itself on this pass.  A later, duplicate delivery of this same DSN will no longer
				// have a pending entry (it was just promoted) and will fall through to the normal suppression check
				// below, which will correctly suppress it.
				if (type == TxMessageType.DSN)
				{
					final TxDetail msgIdDetail = notificationMessage.getDetail(TxDetailType.MSG_ID);

					if (msgIdDetail != null
							&& RepositoryBiz.promotePendingNotifications(msgIdDetail.getDetailValue(), recRepo, pendingRepo))
						return retVal;
				}

				final String[] recipsArray = origRecips.getDetailValue().split(",");
				for (int idx = 0; idx < recipsArray.length; ++ idx)
					recipsArray[idx] = AbstractCompletionCondition.normalizeFinalRecip(recipsArray[idx]);

				final List<String> recips = Arrays.asList(recipsArray);
				recips.replaceAll(String::toUpperCase);

				final List<String> alreadyReceivedNotifs = recRepo.findByMessageidIgnoreCaseAndAddressInIgnoreCase(
						originalMessageIdDetail.getDetailValue().toUpperCase(), recips);
				if (!alreadyReceivedNotifs.isEmpty())
					retVal = true;
			}
		}

		return retVal;
	}

	/**
	 * {@inheritDoc}
	 * <p>
	 * In addition to purging the duplicate notification store, this also purges pending notification entries
	 * (generated DSNs awaiting confirmation that the gateway has tracked them) that have exceeded the pending
	 * message retention time.  Unlike the duplicate notification store, a pending entry surviving long enough to
	 * be purged here indicates that a generated DSN was never confirmed by the gateway, meaning the original
	 * sender may never have received a delivery notification for the corresponding recipient.  Each purged entry
	 * is logged as a warning so that this condition is not silently lost.
	 */
	@Override
	public void purge()
	{
		super.purge();

		if (pendingRepo == null)
			throw new IllegalArgumentException("Pending notification repository cannot be null");

		final Calendar cal = Calendar.getInstance(Locale.getDefault());
		cal.add(Calendar.HOUR, -pendingMessageRetention);

		final List<PendingNotification> stalePending = pendingRepo.findByCreatedTimeBefore(cal);

		if (!stalePending.isEmpty())
		{
			for (PendingNotification notif : stalePending)
				LOGGER.warn("Pending notification for original message id " + notif.getOriginalMessageId() + " and address "
						+ notif.getAddress() + " (DSN message id " + notif.getDsnMessageId() + ") was not confirmed by the gateway within "
						+ pendingMessageRetention + " hour(s) and is being purged.  The sender of this message may not have received "
						+ "a delivery notification for this recipient.");

			pendingRepo.deleteAll(stalePending);
		}
	}
}
